version: "3.3"

services:

  backend:
    build: ./backend
    restart: always
    labels:
      # Enable Traefik for this specicif "backend" service
      - traefik.enable=true
      # Define the port inside of Docker service to use
      - traefik.http.services.app.loadbalancer.server.port=80
      # Make traefik use this domain in HTTP
      - traefik.http.routers.app-http.entrypoints=http
      - traefik.http.routers.app-http.rule=Host(`blyth.tech`)
      # Use Traefik public network
      - traefik.docker.network=traefik-public

    networks:
      # Use public network created to be shared between Traefik and
      # any other service that need to be publicly available via HTTPS
      - traefik-public


networks:
  traefik-public:
    external: true