version: "3.3"

services:
  traefik:
    image: traefik:v2.3
    ports:
      # Listen on port 80, default for HTTP, necessary to redirect to HTTPS
      - 80:80
      # Listen on port 443, default for HTTPS
      - 443:443
    restart: always
    volumes:
      # Add Docker as a mounted volume, so Traefik ca read labels of other services
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Mount the volume to store the certificates
      - traefik-public-certificates:/certificates
    command:
      # Enable Docker in Traefik, so that it reads labels from Dovker services
      - --providers.docker
      # Do not expose Docker service, only the ones explicitly exposed
      - --providers.docker.exposedbydefault=false
      # Create an entrypoint "http" listening on port 80
      - --entrypoints.http.address=:80
      # Create an entrypoint "https" listening on port 443
      - --entrypoints.http.address=:443
      # Create the certificate resolver "le" for Let's Encrypt, uses the environment variable EMAIL
      - --certificatesresolvers.le.acme.email=blythcorn@gmail.com
      # Store the Let's Encrypt certificates in the mounted volume
      - --certificatesresolvers.le.acme.storage=/certificates/acme.json
      # Use the TLS Challenge for Let's Encrypt
      - --certificatesresolvers.le.acme.tlschallenge=true
      # Enable access log, with http requests
      - --accesslog
      # Enable Traefik log, for configurations and errors
      - --log
    networks:
      # Use public network created to be shared between Traefik and
      # any other service that need to be publicly available via HTTPS
      - traefik-public

volumes:
  # Create the volume to store the certificates, theres is a constrain to make sure
  # Traefik is always deployed to the same Docker node with the same volume containing
  # the HTTPS Certificates
  traefik-public-certificates:

networks:
  traefik-public:
    external: true